site_name: PTO Official Documentations
repo_url: https://github.com/bhirawa-mx/PTODocs
site_description: This is official documentation for PTO include user guide and issues tracker.
site_dir: 'build/docs'
markdown_extensions:
 - admonition
nav: 
  - Home: 'index.md'
  - 'User Guide':
      - 'Initial setup': 'setup/initial-setup.md'
      #- 'User administration': 'admin/user-admin.md'
      - 'Input Soal':
          - 'Manual input': 'input/input-soal-manual.md'
          - 'Upload': 'input/input-soal-upload.md'
          - 'Bank Soal': 'input/input-soal-bank.md'
      - 'Paket Soal':
          - 'Assessment A': 'paket-soal/assessment-a.md'
          - 'Assessment B': 'paket-soal/assessment-a.md'
          - 'Assessment C': 'paket-soal/assessment-a.md'
          - 'Tugas': 'paket-soal/assessment-a.md'
      - 'Assessment Type': 'assesment-type.md'
      - 'Glosarium': 'glosarium.md'
  - FAQ: 'faq.md'
