name: Copy build file to Kipin Classroom

on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      commit_msg:
        description: 'Commit message '
        required: true
        default: 'A new version of docs created and pushed by github actions'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes PTO/site file to web/public
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'PTO/build/docs'
        destination_repo: 'mahoni-coder/PTO'
        destination_folder: 'web/public'
        destination_branch: 'kipin-classroom'
        user_email: 'bhirawa@indonesia-commerce.com'
        user_name: 'bhirawa-mx'
        commit_message: ${{ github.event.inputs.commit_msg }}